### ISSUE TITLE
Chapter 6: Databases update checklist

### ISSUE THREAD

**Issue by poldham** [wipo-analytics/manual#2]
- [ ] Add Patcit
- [ ] Check all images are current
- [ ] Cross check hyperlinks in texts
- [ ] Search for new python or R libraries for access that may have been missed
